on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.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 }}
          GITHUB_TOKEN: ${{ secrets.testing_key }}